<?php

namespace Maxpou\BeerBundle\Repository;

/**
 * BeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Delete all Breweries entities (and Beer associated)
     * @return integer number of deleted Beers
     */
    public function deleteAll($brewery)
    {
        $query = $this->getEntityManager()
                      ->createQuery('DELETE FROM Maxpou\BeerBundle\Entity\Beer b WHERE b.brewery = :brewery')
                      ->setParameter("brewery", $brewery);

        return $query->execute();
    }
}
