<?php

namespace Maxpou\BeerBundle\Repository;

/**
 * BeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerRepository extends \Doctrine\ORM\EntityRepository
{
}
