<?php

namespace Maxpou\BeerBundle\Repository;

/**
 * BreweryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreweryRepository extends \Doctrine\ORM\EntityRepository
{
}
