<?php

namespace Maxpou\BeerBundle\Repository;

/**
 * BreweryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreweryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Delete all Breweries entities (and Beer associated)
     * @return integer number of deleted Breweries
     */
    public function deleteAll()
    {
        $this
            ->getEntityManager()
            ->createQuery('DELETE FROM Maxpou\BeerBundle\Entity\Beer')
            ->execute();

        $query = $this
                    ->getEntityManager()
                    ->createQuery('DELETE FROM Maxpou\BeerBundle\Entity\Brewery');

        return $query->execute();
    }
}
